services:
  mariadb:
    image: mariadb:10.8
    container_name: crm-mariadb
    ports:
      - ${DB_HOST_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TZ}
    volumes:
      - ./tmp/mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - crm-network

  redis:
    image: redis:6-alpine
    container_name: crm-redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./tmp/redis_data:/data
    restart: always
    networks:
      - crm-network

  phpmyadmin:
    image: phpmyadmin
    container_name: crm-phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_HOST_PORT}
      - TZ=${DB_TZ}
    restart: always
    networks:
      - crm-network

  crm-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: crm-app
    ports:
      - ${CRM_APP_PORT}:8080
      - "2345:2345"
    volumes:
      - ./:/app
    command: air
    environment:
      # 应用运行环境
      ENV: ${ENV}
      # 数据库连接配置
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_HOST_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DBNAME: ${DB_DBNAME}
      DB_TZ: ${DB_TZ}
    depends_on:
      - mariadb
      - redis
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    restart: always
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge