services:
  mariadb:
    image: mariadb:10.8
    container_name: crm-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - ./tmp/mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - crm-network

  redis:
    image: redis:6-alpine
    container_name: crm-redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/data
    restart: always
    networks:
      - crm-network

  phpmyadmin:
    image: phpmyadmin
    container_name: crm-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    restart: always
    networks:
      - crm-network

  crm-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: crm-app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: air
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    environment:
      - ENV=development
    restart: always
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge