services:
  mariadb:
    image: mariadb:10.8
    container_name: crm-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: crm_db
      MARIADB_USER: crm_user
      MARIADB_PASSWORD: crm_pass
    volumes:
      - ./tmp/mariadb_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:6-alpine
    container_name: crm-redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/data
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: crm-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    restart: always

networks:
  crm-network:
    driver: bridge