# CRM Lite 开发环境配置文件
# 本文件包含了开发环境的完整配置，包括服务器、数据库、缓存、认证等模块

# ==================== 服务器配置 ====================
server:
  mode: debug                 # 运行模式: debug(开发), release(生产), test(测试)
  host: "0.0.0.0"            # 监听地址: 0.0.0.0 表示监听所有网络接口
  port: 8080                 # HTTP 服务端口
  timeout: 30s               # HTTP 读写超时时间，防止慢连接占用资源
  wsAddr: ""                 # WebSocket 地址 (ws://)，留空则不启用
  wssAddr: ""                # 安全WebSocket 地址 (wss://)，留空则不启用
  pidFile: "server.pid"      # PID文件路径
  tls:                       # HTTPS/WSS 证书配置
    certFile: ""             # SSL 证书文件路径，留空则使用 HTTP
    keyFile: ""              # SSL 私钥文件路径

# ==================== 日志配置 ====================
logger:
  dir: "./log"               # 日志文件存储目录
  level: 0                   # 日志级别: 0=debug, 1=info, 2=warn, 3=error, 4=panic, 5=fatal
  lineNum: true              # 是否在日志中显示代码行号，便于调试
  filename: "app.log"        # 日志文件名
  maxSize: 100               # 单文件最大大小(MB)
  maxAge: 7                  # 保存天数
  maxBackups: 3              # 最大备份数
  compress: false            # 是否压缩

# ==================== 数据库配置 ====================
db:
  driver: mysql              # 数据库驱动: mysql, sqlite3
  host: "localhost"          # 数据库服务器地址
  port: 3306                 # 数据库端口 (MySQL/MariaDB 默认 3306)
  user: "crm_user"           # 数据库用户名
  password: "crm_pass"       # 数据库密码
  dbname: "crm_db"           # 数据库名称
  sslmode: disable           # (主要用于PostgreSQL) SSL模式: disable, require, verify-ca, verify-full
  timeZone: "Asia/Shanghai"  # 数据库时区设置
  maxOpenConns: 100          # 最大活跃连接数，根据服务器性能调整
  maxIdleConns: 10           # 最大空闲连接数，保持一定数量提高性能
  connMaxLifetime: 1h        # 连接最大存活时间，防止长时间连接导致的问题

# ==================== 缓存配置 ====================
cache:
  driver: redis              # 缓存驱动: redis, memcached
  redis:
    host: "localhost"        # Redis 服务器地址
    port: 6379              # Redis 端口
    password: ""            # Redis 密码，留空表示无密码
    db: 0                   # Redis 数据库编号 (0-15)
    maxRetries: 3           # 连接失败最大重试次数
    poolSize: 10            # 连接池大小，根据并发量调整
    minIdleConns: 5         # 最小空闲连接数
    maxConnAge: 1h          # 连接最大存活时间
    idleTimeout: 5m         # 空闲连接超时时间
    dialTimeout: 5s         # 连接超时时间
    readTimeout: 3s         # 读取超时时间
    writeTimeout: 3s        # 写入超时时间

# ==================== 认证授权配置 ====================
auth:
  jwt:
    secret: "dev-secret"           # JWT 签名密钥，生产环境务必使用复杂密钥
    issuer: "crm_lite"             # JWT 发行者标识
    algorithm: "HS256"             # 签名算法: HS256, HS384, HS512
    expire_duration: 3600s         # 默认 token 过期时间 (秒)
    access_token_expire: 3600s     # 访问令牌过期时间 (1小时)
    refresh_token_expire: 3600s    # 刷新令牌过期时间 (建议设置更长时间)
  rbac:
    modelFile: "internal/bootstrap/model.conf"
  oauthEnabled: false              # 是否启用第三方 OAuth 登录 (如微信、钉钉等)
  BCryptCost: 12                   # 密码加密强度: 10-12 适合生产环境
  superAdmin:
    username: admin
    password: "PLEASE_CHANGE_ME_IN_PRODUCTION"
    email: "admin@yourdomain.com"
    role: "super_admin"
  # 默认角色配置
  default_role: "authenticated_user"

# ==================== 邮件服务配置 (SMTP) ====================
email:
  host: "smtp.gmail.com"         # SMTP 服务器地址
  port: 587                      # SMTP 端口 (587 for TLS, 465 for SSL)
  username: "your-email@gmail.com" # 您的 Gmail 邮箱
  # 推荐使用环境变量设置密码: export EMAIL_PASSWORD=your_gmail_app_password
  password: "your-gmail-app-password"                   # 您的 Gmail 应用专用密码 (App Password)
  from: "your-email@gmail.com"   # 发件人邮箱，通常与 username 相同
  fromName: "CRM Lite Support"   # 发件人显示名称
  useTLS: true                   # 是否强制使用 STARTTLS
  insecureSkip: false            # 在生产环境中应始终为 false

# ==================== 性能监控配置 ====================
pprofOn: true                      # 是否启用 pprof 性能分析，生产环境建议关闭