# ===================================================================
#                      TESTING ENVIRONMENT
#
# IMPORTANT: This configuration is for the test environment.
# Please ensure the database specified here is a dedicated test database
# as tests may truncate or delete data.
# ===================================================================

# CRM Lite 开发环境配置文件
# 本文件包含了开发环境的完整配置，包括服务器、数据库、缓存、认证等模块

# ==================== 服务器配置 ====================
server:
  mode: test
  host: "127.0.0.1"
  port: 8081 # Use a different port for testing to avoid conflicts
  timeout: 30s
  pidFile: "server_test.pid"

# ==================== 日志配置 ====================
logger:
  dir: "logs"
  filename: "test.log"
  level: -1 # Debug level
  lineNum: true
  maxSize: 10
  maxAge: 3
  maxBackups: 5
  compress: false

# ==================== 数据库配置 ====================
db:
  driver: "mysql" # or "postgres"
  host: "127.0.0.1"
  port: 3306
  user: "crm_user"
  password: "crm_pass"
  dbname: "crm_db" # Use a dedicated test database name
  sslmode: "disable"
  timeZone: "Asia/Shanghai"
  maxOpenConns: 10
  maxIdleConns: 5
  connMaxLifetime: 1h

# ==================== 缓存配置 ====================
cache:
  driver: "redis"
  redis:
    host: "127.0.0.1"
    port: 6379
    password: ""
    db: 1 # Use a different Redis DB for testing
    poolSize: 10
    minIdleConns: 5

# ==================== 认证授权配置 ====================
auth:
  jwt:
    secret: "test-secret-key-that-is-long-and-secure"
    issuer: "crm-lite-test"
    access_token_expire: 15m
    refresh_token_expire: 72h
  rbac:
    modelFile: "config/model.conf"
  BCryptCost: 10

# ==================== 性能监控配置 ====================
pprofOn: true