# ===================================================================
#                      TESTING ENVIRONMENT
#
# IMPORTANT: This configuration is for the test environment.
# Please ensure the database specified here is a dedicated test database
# as tests may truncate or delete data.
# ===================================================================

# CRM Lite 开发环境配置文件
# 本文件包含了开发环境的完整配置，包括服务器、数据库、缓存、认证等模块

# ==================== 服务器配置 ====================
server:
  mode: test
  host: "0.0.0.0"
  port: 8080
  timeout: 30s
  pidFile: "server_dev.pid"

# ==================== 日志配置 ====================
logger:
  dir: "logs"
  filename: "dev.log"
  level: -1 # Debug level
  lineNum: true
  maxSize: 10
  maxAge: 1
  maxBackups: 5
  compress: false
  enableTimeRotation: true    # 启用按时间轮转
  rotationTime: "daily"       # 轮转间隔: hourly, daily, weekly
  linkName: "current.log"     # 当前日志文件的软链接名称

# ==================== 数据库配置 ====================
db:
  driver: mysql # 数据库驱动: mysql, sqlite3
  host: mariadb # 数据库服务器地址
  port: 3306 # 数据库端口 (MySQL/MariaDB 默认 3306)
  user: "crm_user" # 数据库用户名
  password: "crm_pass" # 数据库密码
  dbname: "crm_db" # 数据库名称
  sslmode: disable # (主要用于PostgreSQL) SSL模式: disable, require, verify-ca, verify-full
  timeZone: "Asia/Shanghai" # 数据库时区设置
  maxOpenConns: 10 # 最大活跃连接数
  maxIdleConns: 5 # 最大空闲连接数
  connMaxLifetime: 1h

# ==================== 缓存配置 ====================
cache:
  driver: "redis"
  redis:
    host: "redis"
    port: 6379
    password: ""
    db: 0 # Use a different Redis DB for testing
    poolSize: 10
    minIdleConns: 5

# ==================== 认证授权配置 ====================
auth:
  jwt:
    secret: "test-secret-key-that-is-long-and-secure"
    issuer: "crm-lite-dev"
    access_token_expire: 24h
    refresh_token_expire: 72h
  rbac:
    modelFile: "internal/bootstrap/model.conf"
  BCryptCost: 10
  superAdmin:
    username: "admin"
    password: "admin123"
    email: "admin@example.com"
    role: "super_admin"
  # 默认角色配置
  default_role: "authenticated_user"
  # 人机验证配置
  captcha:
    turnstileSecret: "1x0000000000000000000000000000000AA" # Cloudflare Turnstile Secret Key
# ==================== 邮件服务配置 (SMTP) ====================
email:
  host: "smtp.gmail.com" # SMTP 服务器地址
  port: 587 # SMTP 端口 (587 for TLS, 465 for SSL)
  username: "your-email@gmail.com" # 您的 Gmail 邮箱
  # 推荐使用环境变量设置密码: export EMAIL_PASSWORD=your_gmail_app_password
  password: "your-gmail-app-password" # 您的 Gmail 应用专用密码 (App Password)
  from: "your-email@gmail.com" # 发件人邮箱，通常与 username 相同
  fromName: "CRM Lite Support" # 发件人显示名称
  useTLS: true # 是否强制使用 STARTTLS
  insecureSkip: false # 在生产环境中应始终为 false

# ==================== 日志清理配置 ====================
logCleanup:
  mode: "internal" # internal: 内置调度器, external: 外部调度器
  interval: "1h" # 检查间隔 (仅内置模式有效)
  retentionDay: 1 # 日志保留天数
  dryRun: false # 试运行模式

# ==================== 性能监控配置 ====================
pprofOn: true