development:
  dialect: mysql
  datasource: crm_user:crm_pass@tcp(localhost:3306)/crm_db?parseTime=true
  dir: ./migrations
  table: migrations

test:
  dialect: mysql
  datasource: root:root_password@tcp(localhost:3306)/crm_lite_test?parseTime=true
  dir: ./migrations
  table: migrations

production:
  dialect: mysql
  datasource: crm_user:crm_pass@tcp(localhost:3306)/crm_db?parseTime=true
  dir: ./migrations
  table: migrations