development:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_DBNAME}?parseTime=true
  dir: db/migrations
  table: migrations

test:
  dialect: mysql
  datasource: root:root_password@tcp(${DB_HOST}:3306)/crm_lite_test?parseTime=true
  dir: db/migrations
  table: migrations

production:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_DBNAME}?parseTime=true
  dir: db/migrations
  table: migrations