package routes

import (
	"crm_lite/internal/core/config"
	"crm_lite/internal/core/resource"
	"crm_lite/internal/middleware"
	"crm_lite/pkg/resp"

	"github.com/gin-gonic/gin"

	// docs is generated by Swag CLI
	_ "crm_lite/docs"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func NewRouter(resManager *resource.Manager) *gin.Engine {
	// 1. 设置Gin模式
	gin.SetMode(string(config.GetInstance().Server.Mode))
	router := gin.New()

	// 2. 注册通用中间件
	router.Use(middleware.GinLogger(), gin.Recovery())

	// 3. 创建 /api/v1 路由组
	apiV1 := router.Group("/api/v1")
	{
		// 3.1 注册公共路由 (无需登录)
		registerAuthRoutes(apiV1, resManager) // 登录、注册等接口

		// 3.2 注册受保护的路由 (需要登录和权限验证)
		// 注意：中间件是应用在子分组上的，而不是整个 apiV1
		adminGroup := apiV1.Group("")
		adminGroup.Use(middleware.JWTAuthMiddleware(resManager), middleware.CasbinMiddleware(resManager))
		{
			registerUserRoutes(adminGroup, resManager)
			registerRoleRoutes(adminGroup, resManager)
			registerPermissionRoutes(adminGroup, resManager)
			registerCustomerRoutes(adminGroup, resManager)
			// 未来新的受保护路由也在这里注册...
		}
	}

	// 4. 设置一些通用路由
	// 健康检查
	router.GET("/health", func(c *gin.Context) {
		resp.Success(c, "ok")
	})

	// 欢迎页
	router.GET("/", func(c *gin.Context) {
		resp.Success(c, "Hello, World!")
	})
	// Add Swagger UI route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return router
}
