name: Build Dev Environment

on:
  push:
    branches:
      - dev
      - feature/**

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run dev build
        run: npm run build:dev 