# 本 workflow 可用 act 本地调试，需在项目根目录添加 .secrets 文件，内容参考 GitHub Actions secrets。

name: Release to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git Tag for Release'
        required: true

jobs:
  build-and-push-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -v -o app .

      - name: Build Docker image (tag & prod)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.event.inputs.tag }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.event.inputs.tag }} ${{ secrets.DOCKER_USERNAME }}/myapp:prod

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image (tag & prod)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.event.inputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:prod