name: Release to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git Tag for Release'
        required: true

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run production build
        run: npm run build

      - name: Deploy to production server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "dist/"
          target: "/var/www/production" 