# 本 workflow 可用 act 本地调试，需在项目根目录添加 .secrets 文件，内容参考 GitHub Actions secrets。
name: Build & Push Staging Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -v -o app .

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:staging .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image (staging)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:staging