// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminUserRole = "admin_user_roles"

// AdminUserRole mapped from table <admin_user_roles>
type AdminUserRole struct {
	ID          string    `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	AdminUserID string    `gorm:"column:admin_user_id;type:varchar(36);not null;uniqueIndex:admin_user_id,priority:1;index:idx_admin_user_roles_admin_user_id,priority:1" json:"admin_user_id"`
	RoleID      string    `gorm:"column:role_id;type:varchar(36);not null;uniqueIndex:admin_user_id,priority:2;index:idx_admin_user_roles_role_id,priority:1" json:"role_id"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
}

// TableName AdminUserRole's table name
func (*AdminUserRole) TableName() string {
	return TableNameAdminUserRole
}
