// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameContact = "contacts"

// Contact mapped from table <contacts>
type Contact struct {
	ID         int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CustomerID int64          `gorm:"column:customer_id;type:bigint(20);not null;index:idx_contacts_customer_id,priority:1" json:"customer_id"`
	Name       string         `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Phone      string         `gorm:"column:phone;type:varchar(20);index:idx_contacts_phone,priority:1" json:"phone"`
	Email      string         `gorm:"column:email;type:varchar(100);index:idx_contacts_email,priority:1" json:"email"`
	Position   string         `gorm:"column:position;type:varchar(50);comment:职位" json:"position"`                                                 // 职位
	IsPrimary  bool           `gorm:"column:is_primary;type:tinyint(1);index:idx_contacts_is_primary,priority:1;comment:是否主联系人" json:"is_primary"` // 是否主联系人
	Note       string         `gorm:"column:note;type:text" json:"note"`
	CreatedAt  time.Time      `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(6);index:idx_contacts_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Contact's table name
func (*Contact) TableName() string {
	return TableNameContact
}
