// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMarketingRecord = "marketing_records"

// MarketingRecord mapped from table <marketing_records>
type MarketingRecord struct {
	ID           string    `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	CampaignID   string    `gorm:"column:campaign_id;type:varchar(36);not null;index:idx_marketing_records_campaign_id,priority:1" json:"campaign_id"`
	CustomerID   string    `gorm:"column:customer_id;type:varchar(36);not null;index:idx_marketing_records_customer_id,priority:1" json:"customer_id"`
	ContactID    string    `gorm:"column:contact_id;type:varchar(36);index:idx_marketing_records_contact_id,priority:1" json:"contact_id"`
	Channel      string    `gorm:"column:channel;type:varchar(20);not null;index:idx_marketing_records_channel,priority:1;comment:触达渠道" json:"channel"`                                                                             // 触达渠道
	Status       string    `gorm:"column:status;type:varchar(20);index:idx_marketing_records_status,priority:1;default:pending;comment:状态: pending, sent, delivered, failed, opened, clicked, replied, unsubscribed" json:"status"` // 状态: pending, sent, delivered, failed, opened, clicked, replied, unsubscribed
	ErrorMessage string    `gorm:"column:error_message;type:text;comment:发送失败时的错误信息" json:"error_message"`                                                                                                                          // 发送失败时的错误信息
	Response     string    `gorm:"column:response;type:longtext;comment:客户反馈或互动数据" json:"response"`                                                                                                                                 // 客户反馈或互动数据
	SentAt       time.Time `gorm:"column:sent_at;type:datetime(6);index:idx_marketing_records_sent_at,priority:1" json:"sent_at"`
	DeliveredAt  time.Time `gorm:"column:delivered_at;type:datetime(6);index:idx_marketing_records_delivered_at,priority:1" json:"delivered_at"`
	OpenedAt     time.Time `gorm:"column:opened_at;type:datetime(6);index:idx_marketing_records_opened_at,priority:1;comment:打开时间（邮件/推送）" json:"opened_at"` // 打开时间（邮件/推送）
	ClickedAt    time.Time `gorm:"column:clicked_at;type:datetime(6);index:idx_marketing_records_clicked_at,priority:1;comment:点击时间" json:"clicked_at"`     // 点击时间
	RepliedAt    time.Time `gorm:"column:replied_at;type:datetime(6);comment:回复时间" json:"replied_at"`                                                       // 回复时间
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
}

// TableName MarketingRecord's table name
func (*MarketingRecord) TableName() string {
	return TableNameMarketingRecord
}
