// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMarketingCampaign = "marketing_campaigns"

// MarketingCampaign mapped from table <marketing_campaigns>
type MarketingCampaign struct {
	ID                int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	Name              string         `gorm:"column:name;type:varchar(200);not null;index:idx_marketing_campaigns_name,priority:1" json:"name"`
	Type              string         `gorm:"column:type;type:varchar(20);not null;index:idx_marketing_campaigns_type,priority:1;comment:营销类型: sms, email, push_notification, wechat, call" json:"type"`                    // 营销类型: sms, email, push_notification, wechat, call
	Status            string         `gorm:"column:status;type:varchar(20);index:idx_marketing_campaigns_status,priority:1;default:draft;comment:状态: draft, scheduled, active, paused, completed, archived" json:"status"` // 状态: draft, scheduled, active, paused, completed, archived
	TargetTags        string         `gorm:"column:target_tags;type:longtext;comment:目标客户标签" json:"target_tags"`                                                                                                           // 目标客户标签
	TargetSegmentID   int64          `gorm:"column:target_segment_id;type:bigint(20);comment:目标客户分群ID（如果有客户分群功能）" json:"target_segment_id"`                                                                                // 目标客户分群ID（如果有客户分群功能）
	ContentTemplateID int64          `gorm:"column:content_template_id;type:bigint(20);comment:内容模板ID（如果有模板功能）" json:"content_template_id"`                                                                                // 内容模板ID（如果有模板功能）
	Content           string         `gorm:"column:content;type:text;not null;comment:活动具体内容或模板变量的JSON数据" json:"content"`                                                                                                  // 活动具体内容或模板变量的JSON数据
	StartTime         time.Time      `gorm:"column:start_time;type:datetime(6);index:idx_marketing_campaigns_start_time,priority:1" json:"start_time"`
	EndTime           time.Time      `gorm:"column:end_time;type:datetime(6);index:idx_marketing_campaigns_end_time,priority:1" json:"end_time"`
	ActualStartTime   time.Time      `gorm:"column:actual_start_time;type:datetime(6)" json:"actual_start_time"`
	ActualEndTime     time.Time      `gorm:"column:actual_end_time;type:datetime(6)" json:"actual_end_time"`
	TargetCount       int32          `gorm:"column:target_count;type:int(11);comment:目标客户数量" json:"target_count"`                                                 // 目标客户数量
	SentCount         int32          `gorm:"column:sent_count;type:int(11);comment:已发送数量" json:"sent_count"`                                                      // 已发送数量
	SuccessCount      int32          `gorm:"column:success_count;type:int(11);comment:成功数量" json:"success_count"`                                                 // 成功数量
	ClickCount        int32          `gorm:"column:click_count;type:int(11);comment:点击数量" json:"click_count"`                                                     // 点击数量
	CreatedBy         int64          `gorm:"column:created_by;type:bigint(20);index:idx_marketing_campaigns_created_by,priority:1;comment:创建人" json:"created_by"` // 创建人
	UpdatedBy         int64          `gorm:"column:updated_by;type:bigint(20);comment:更新人" json:"updated_by"`                                                     // 更新人
	CreatedAt         time.Time      `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(6);index:idx_marketing_campaigns_deleted_at,priority:1" json:"deleted_at"`
}

// TableName MarketingCampaign's table name
func (*MarketingCampaign) TableName() string {
	return TableNameMarketingCampaign
}
