// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMigration = "migrations"

// Migration mapped from table <migrations>
type Migration struct {
	ID        string    `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`
	AppliedAt time.Time `gorm:"column:applied_at;type:datetime" json:"applied_at"`
}

// TableName Migration's table name
func (*Migration) TableName() string {
	return TableNameMigration
}
