// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID             string         `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	OrderNo        string         `gorm:"column:order_no;type:varchar(50);not null;uniqueIndex:order_no,priority:1" json:"order_no"`
	CustomerID     string         `gorm:"column:customer_id;type:varchar(36);not null;index:idx_orders_cust_date,priority:1" json:"customer_id"`
	ContactID      string         `gorm:"column:contact_id;type:varchar(36)" json:"contact_id"`
	OrderDate      time.Time      `gorm:"column:order_date;type:datetime(6);not null;index:idx_orders_cust_date,priority:2" json:"order_date"`
	Status         string         `gorm:"column:status;type:varchar(20);not null;index:idx_orders_status,priority:1;default:draft;comment:订单状态: draft, pending, confirmed, processing, shipped, completed, cancelled, refunded" json:"status"` // 订单状态: draft, pending, confirmed, processing, shipped, completed, cancelled, refunded
	PaymentStatus  string         `gorm:"column:payment_status;type:varchar(20);not null;index:idx_orders_pay_status,priority:1;default:unpaid;comment:支付状态: unpaid, paid, partially_paid, refunded, pending" json:"payment_status"`           // 支付状态: unpaid, paid, partially_paid, refunded, pending
	TotalAmount    float64        `gorm:"column:total_amount;type:decimal(12,2);not null;default:0.00" json:"total_amount"`
	DiscountAmount float64        `gorm:"column:discount_amount;type:decimal(12,2);not null;default:0.00" json:"discount_amount"`
	FinalAmount    float64        `gorm:"column:final_amount;type:decimal(12,2);not null" json:"final_amount"`
	PaymentMethod  string         `gorm:"column:payment_method;type:varchar(20);index:idx_orders_pay_status,priority:2;comment:支付方式: online, offline_transfer, cash_on_delivery, wallet_balance" json:"payment_method"` // 支付方式: online, offline_transfer, cash_on_delivery, wallet_balance
	Remark         string         `gorm:"column:remark;type:text" json:"remark"`
	AssignedTo     string         `gorm:"column:assigned_to;type:varchar(36);index:idx_orders_assigned_open,priority:1" json:"assigned_to"`
	CreatedBy      string         `gorm:"column:created_by;type:varchar(36)" json:"created_by"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(6)" json:"deleted_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
