// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID          int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;type:varchar(50);not null;uniqueIndex:name,priority:1" json:"name"`
	DisplayName string         `gorm:"column:display_name;type:varchar(100);not null" json:"display_name"`
	Description string         `gorm:"column:description;type:text" json:"description"`
	IsActive    bool           `gorm:"column:is_active;type:tinyint(1);default:1" json:"is_active"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(6);index:idx_roles_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
