// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysOutbox = "sys_outbox"

// SysOutbox 系统事件发布表，支持Outbox模式
type SysOutbox struct {
	ID          int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	EventType   string `gorm:"column:event_type;type:varchar(64);not null;index:idx_type_time,priority:1;comment:事件类型：order.placed, wallet.credited等" json:"event_type"` // 事件类型：order.placed, wallet.credited等
	Payload     string `gorm:"column:payload;type:longtext;not null;comment:事件载荷数据" json:"payload"`                                                                      // 事件载荷数据
	CreatedAt   int64  `gorm:"column:created_at;type:bigint(20);not null;index:idx_type_time,priority:2;comment:创建时间（Unix时间戳）" json:"created_at"`                        // 创建时间（Unix时间戳）
	ProcessedAt int64  `gorm:"column:processed_at;type:bigint(20);index:idx_processed,priority:1;comment:处理时间（Unix时间戳），NULL表示未处理" json:"processed_at"`                   // 处理时间（Unix时间戳），NULL表示未处理
}

// TableName SysOutbox's table name
func (*SysOutbox) TableName() string {
	return TableNameSysOutbox
}
