// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWallet = "wallets"

// Wallet mapped from table <wallets>
type Wallet struct {
	ID             string    `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	CustomerID     string    `gorm:"column:customer_id;type:varchar(36);not null;uniqueIndex:customer_id,priority:1" json:"customer_id"`
	Type           string    `gorm:"column:type;type:varchar(20);uniqueIndex:customer_id,priority:2;default:balance;comment:钱包类型: balance, points, coupon, deposit" json:"type"` // 钱包类型: balance, points, coupon, deposit
	Balance        float64   `gorm:"column:balance;type:decimal(10,2);not null;index:idx_wallets_balance,priority:1;default:0.00" json:"balance"`
	FrozenBalance  float64   `gorm:"column:frozen_balance;type:decimal(10,2);default:0.00;comment:冻结金额" json:"frozen_balance"`   // 冻结金额
	TotalRecharged float64   `gorm:"column:total_recharged;type:decimal(10,2);default:0.00;comment:累计充值" json:"total_recharged"` // 累计充值
	TotalConsumed  float64   `gorm:"column:total_consumed;type:decimal(10,2);default:0.00;comment:累计消费" json:"total_consumed"`   // 累计消费
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
}

// TableName Wallet's table name
func (*Wallet) TableName() string {
	return TableNameWallet
}
