// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWalletTransaction = "wallet_transactions"

// WalletTransaction mapped from table <wallet_transactions>
type WalletTransaction struct {
	ID             int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	WalletID       int64  `gorm:"column:wallet_id;type:bigint(20);not null;index:idx_wallet_time,priority:1;comment:钱包ID" json:"wallet_id"`                                          // 钱包ID
	Direction      string `gorm:"column:direction;type:enum('credit','debit');not null;comment:资金方向：credit-入账，debit-出账" json:"direction"`                                            // 资金方向：credit-入账，debit-出账
	Amount         int64  `gorm:"column:amount;type:bigint(20);not null;comment:交易金额（分），始终为正数" json:"amount"`                                                                        // 交易金额（分），始终为正数
	Type           string `gorm:"column:type;type:enum('recharge','order_pay','order_refund','adjust_in','adjust_out');not null;index:idx_type,priority:1;comment:交易类型" json:"type"` // 交易类型
	BizRefType     string `gorm:"column:biz_ref_type;type:varchar(32);index:idx_biz_ref,priority:1;comment:业务引用类型：order/refund/manual等" json:"biz_ref_type"`                         // 业务引用类型：order/refund/manual等
	BizRefID       int64  `gorm:"column:biz_ref_id;type:bigint(20);index:idx_biz_ref,priority:2;comment:业务引用ID，如订单ID" json:"biz_ref_id"`                                             // 业务引用ID，如订单ID
	IdempotencyKey string `gorm:"column:idempotency_key;type:varchar(64);not null;uniqueIndex:uk_idempotency,priority:1;comment:幂等键，防止重复交易" json:"idempotency_key"`                  // 幂等键，防止重复交易
	OperatorID     int64  `gorm:"column:operator_id;type:bigint(20);index:idx_operator,priority:1;comment:操作员ID" json:"operator_id"`                                                 // 操作员ID
	ReasonCode     string `gorm:"column:reason_code;type:varchar(32);comment:交易原因代码" json:"reason_code"`                                                                             // 交易原因代码
	Note           string `gorm:"column:note;type:varchar(255);comment:备注信息" json:"note"`                                                                                            // 备注信息
	CreatedAt      int64  `gorm:"column:created_at;type:bigint(20);not null;index:idx_wallet_time,priority:2;comment:创建时间（Unix时间戳）" json:"created_at"`                               // 创建时间（Unix时间戳）
}

// TableName WalletTransaction's table name
func (*WalletTransaction) TableName() string {
	return TableNameWalletTransaction
}
