// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWallet = "wallets"

// Wallet mapped from table <wallets>
type Wallet struct {
	ID         int64     `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CustomerID int64     `gorm:"column:customer_id;type:bigint(20);not null;uniqueIndex:customer_id,priority:1;index:idx_wallets_customer,priority:1;comment:客户ID，每个客户只有一个钱包" json:"customer_id"` // 客户ID，每个客户只有一个钱包
	Balance    int64     `gorm:"column:balance;type:bigint(20);not null;comment:当前余额（分），只读字段，由交易聚合计算" json:"balance"`                                                                             // 当前余额（分），只读字段，由交易聚合计算
	Status     int32     `gorm:"column:status;type:tinyint(4);not null;index:idx_wallets_status,priority:1;default:1;comment:钱包状态：1-正常，0-冻结" json:"status"`                                       // 钱包状态：1-正常，0-冻结
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt  int64     `gorm:"column:updated_at;type:bigint(20);not null;comment:Unix时间戳，用于乐观锁" json:"updated_at"` // Unix时间戳，用于乐观锁
}

// TableName Wallet's table name
func (*Wallet) TableName() string {
	return TableNameWallet
}
